# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-19 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFileModel',
            new_name='VirusModel',
        ),
    ]
