# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-20 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_virusmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='virusmodel',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
