# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_signature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signature',
            new_name='Signature_sha256',
        ),
    ]
