# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20170524_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VirusString',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='VirusUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Signature_sha256',
        ),
        migrations.AddField(
            model_name='virusdatabase',
            name='string',
            field=models.ManyToManyField(to='analysis.VirusString'),
        ),
        migrations.AddField(
            model_name='virusdatabase',
            name='url',
            field=models.ManyToManyField(to='analysis.VirusUrl'),
        ),
    ]
