# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_auto_20170525_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirusFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='VirusString',
        ),
        migrations.AlterField(
            model_name='virusdatabase',
            name='string',
            field=models.ManyToManyField(to='analysis.VirusFunction'),
        ),
    ]
