# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-25 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0009_auto_20170525_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virusdatabase',
            old_name='string',
            new_name='function',
        ),
    ]
